name: Release workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set variables
        run: |
          echo "VERSION=$(echo $GITHUB_REF_NAME | tr -d 'v')" >> $GITHUB_ENV
          echo "GROUP=com.hibob" >> $GITHUB_ENV

      - name: Build and Publish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: ./gradlew -PcustomGroup=$GROUP -PcustomVersion=$VERSION -Porg.gradle.java.installations.auto-download=false --no-daemon --build-cache test publish --rerun-tasks
